# Latent Dirichlet Allocation

Following Mirko Draca and Carlo Schwarz selection of WVS questions and waves

In [85]:
pip install -r requirements.txt

Requirement already satisfied: numpy in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: pandas in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: matplotlib in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (3.10.0)
Requirement already satisfied: seaborn in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (0.13.2)
Requirement already satisfied: scipy in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (1.15.2)
Requirement already satisfied: scikit-learn in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (1.6.1)
Requirement already satisfied: rpy2 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (3.5.17)
Requirement already satisfied: geopandas in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (1.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from pandas->-r requirements.txt (line 2)) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from pandas->-r requirements.txt (line 2)) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (24.2)
Requirement already satisfied: pillow>=8 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 3)) (3.2.1)
Requirement already satisfied: joblib>=1.2.0 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from scikit-learn->-r requirements.txt (line 6)) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from scikit-learn->-r requirements.txt (line 6)) (3.5.0)
Requirement already satisfied: cffi>=1.15.1 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from rpy2->-r requirements.txt (line 7)) (1.17.1)
Requirement already satisfied: jinja2 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from rpy2->-r requirements.txt (line 7)) (3.1.5)
Requirement already satisfied: tzlocal in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from rpy2->-r requirements.txt (line 7)) (5.3)
Requirement already satisfied: pyogrio>=0.7.2 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from geopandas->-r requirements.txt (line 8)) (0.10.0)
Requirement already satisfied: pyproj>=3.3.0 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from geopandas->-r requirements.txt (line 8)) (3.7.1)
Requirement already satisfied: shapely>=2.0.0 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from geopandas->-r requirements.txt (line 8)) (2.1.0)
Requirement already satisfied: pycparser in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from cffi>=1.15.1->rpy2->-r requirements.txt (line 7)) (2.22)
Requirement already satisfied: certifi in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from pyogrio>=0.7.2->geopandas->-r requirements.txt (line 8)) (2025.1.31)
Requirement already satisfied: six>=1.5 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/aranxamarquezampudia/miniconda3/envs/NLP/lib/python3.10/site-packages (from jinja2->rpy2->-r requirements.txt (line 7)) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [19]:
import os
import pandas as pd

df_wvs = pd.read_csv('../data/raw/wvs_ts_w1_w7.csv')

## Encoding Survey Answers

In [60]:
def recode_survey_responses(df_wvs, question_columns, neutral_values={3, 5}):
    """
    Following Draca & Schwarz (2024) methodology, this function recodes responses from WVS waves 4-7 
    into support and oppose indicators, imputes missing values, and filters countries based on response completeness.

    Parameters:
    - df_wvs (pd.DataFrame): Survey DataFrame.
    - question_columns (list): List of columns to transform.
    - neutral_values (set): Values representing neutrality (not used here but can be extended).
    
    Returns:
    - pd.DataFrame: Transformed DataFrame with support/oppose indicators and country/year.
    """
    # Step 1: Rename and filter for years >= 1999
    new_df = df_wvs.rename(columns={"COUNTRY_ALPHA": "country", "S020": "year", "S002VS": "wave"}) \
                   .loc[lambda df: df["year"] >= 1999] \
                   .copy()

    # Step 2: Filter for relevant waves
    valid_waves = [4, 5, 6, 7]
    df_filtered = new_df[new_df["wave"].isin(valid_waves)].copy()

    # Step 3: Find countries that appear in at least 3 of the 4 waves
    wave_counts = df_filtered.groupby("country")["wave"].nunique()
    eligible_countries = wave_counts[wave_counts >= 3].index
    df_final = df_filtered[df_filtered["country"].isin(eligible_countries)].copy()

    # Step 4: Impute missing values for each question column
    for col in question_columns:
        valid_values = df_final[df_final[col] >= 0][col]
        mean_value = valid_values.mean()
        df_final[col] = df_final[col].apply(lambda x: mean_value if x < 0 else x)

    # Step 5: Recode into support and oppose
    for col in question_columns:
        if col == "C002":  # 1–3 scale (agree-disagree)
            df_final[f"{col}_support"] = df_final[col].apply(lambda x: 1 if x == 1 else 0)
            df_final[f"{col}_oppose"] = df_final[col].apply(lambda x: 1 if x == 2 else 0)
        elif col in ["G006", "E069_01", "E069_02", "E069_04", "E069_05", "E069_06",
             "E069_07", "E069_08", "E069_13", "E069_17"]:  # 1–4 scale
             df_final[f"{col}_support"] = df_final[col].apply(lambda x: 1 if x in [1, 2] else 0)
             df_final[f"{col}_oppose"] = df_final[col].apply(lambda x: 1 if x in [3, 4] else 0)
        elif col in ["E036", "E037", "E039"] or "F1" in col:  # 1–10 scale
            df_final[f"{col}_support"] = df_final[col].apply(lambda x: 1 if x >= 6 else 0)
            df_final[f"{col}_oppose"] = df_final[col].apply(lambda x: 1 if x <= 4 else 0)
        else:  # Binary 0–1
            df_final[f"{col}_support"] = df_final[col]
            df_final[f"{col}_oppose"] = 1 - df_final[col]

    # Step 6: Keep only relevant columns
    interest_columns = ["country", "year"] + \
                       [f"{col}_support" for col in question_columns] + \
                       [f"{col}_oppose" for col in question_columns]

    return df_final[interest_columns]

In [69]:
# Test the function
question_columns = [
    "A124_02", "A124_06", "A124_07", "A124_08", "A124_09", "C002", "E036", "E037", "E039",
    "F114A", "F115", "F116", "F117", "F118", "F119", "F120", "F121", "F122", "F123", "G006", 
    "E069_01", "E069_02", "E069_04", "E069_05", "E069_06", "E069_07", "E069_08", "E069_13", "E069_17"
]

In [70]:
df_encoded = recode_survey_responses(df_wvs, question_columns)

/var/folders/vk/c6csf7ws6pj9wy406twfjkfw0000gn/T/ipykernel_31029/4208553163.py:41: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[f"{col}_support"] = df_final[col].apply(lambda x: 1 if x in [1, 2] else 0)
/var/folders/vk/c6csf7ws6pj9wy406twfjkfw0000gn/T/ipykernel_31029/4208553163.py:42: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final[f"{col}_oppose"] = df_final[col].apply(lambda x: 1 if x in [3, 4] else 0)

In [ ]:
## Exploring transformed file
# Check the first few rows of the transformed DataFrame

print(df_encoded.head())

     country  year  A124_02_support  A124_06_support  A124_07_support  \
7092     ARG  1999              0.0              0.0              0.0
7093     ARG  1999              0.0              0.0              0.0
7094     ARG  1999              0.0              0.0              1.0
7095     ARG  1999              0.0              0.0              0.0
7096     ARG  1999              0.0              0.0              0.0

      A124_08_support  A124_09_support  C002_support  E036_support  \
7092              0.0              0.0             0             0
7093              1.0              0.0             1             1
7094              1.0              1.0             1             1
7095              0.0              0.0             0             0
7096              0.0              0.0             1             0

      E037_support  ...  G006_oppose  E069_01_oppose  E069_02_oppose  \
7092             1  ...            0               0               1
7093             0  ...            0               0               1
7094             0  ...            0               0               1
7095             0  ...            0               1               1
7096             1  ...            0               1               1

      E069_04_oppose  E069_05_oppose  E069_06_oppose  E069_07_oppose  \
7092               1               1               1               1
7093               1               1               1               1
7094               1               1               1               1
7095               1               1               0               1
7096               0               1               1               1

      E069_08_oppose  E069_13_oppose  E069_17_oppose
7092               1               1               0
7093               1               1               0
7094               1               1               0
7095               1               0               0
7096               1               0               0

[5 rows x 60 columns]

## Splitting the data into the corresponding waves

In [118]:
### Split the data frame in the four waves

# Wave 4 1999 - 2004
df_wave4 = df_encoded[df_encoded['year'].between(1999, 2004)].copy()

# Wave 5 2005 - 2009
df_wave5 = df_encoded[df_encoded['year'].between(2005, 2009)].copy()

# Wave 6 2010 - 2014
df_wave6 = df_encoded[df_encoded['year'].between(2010, 2014)].copy()

# Wave 7 2017 - 2022
df_wave7 = df_encoded[df_encoded['year'].between(2017, 2022)].copy()

# Save the transformed DataFrames to CSV files in the output directory data/processed
output_dir = '../data/processed'
os.makedirs(output_dir, exist_ok=True)
df_encoded.to_csv(os.path.join(output_dir, 'wvs_encoded.csv'), index=False)
df_wave4.to_csv(os.path.join(output_dir, 'wvs_wave4.csv'), index=False)
df_wave5.to_csv(os.path.join(output_dir, 'wvs_wave5.csv'), index=False)
df_wave6.to_csv(os.path.join(output_dir, 'wvs_wave6.csv'), index=False)
df_wave7.to_csv(os.path.join(output_dir, 'wvs_wave7.csv'), index=False)

In [ ]:
## Check the dimensions of all the frames (wave 4-7)
for i, df in enumerate([df_wave4, df_wave5, df_wave6, df_wave7], start=4):
    print(f"Wave {i} dimensions: {df.shape}")

Wave 4 dimensions: (46100, 60)
Wave 5 dimensions: (57982, 60)
Wave 6 dimensions: (60783, 60)
Wave 7 dimensions: (62706, 60)

In [86]:
# Column names of the transformed DataFrames
print("Column names of the transformed DataFrames:")
for i, df in enumerate([df_wave4, df_wave5, df_wave6, df_wave7], start=4):
    print(f"Wave {i} columns: {df.columns.tolist()}")

Column names of the transformed DataFrames:
Wave 4 columns: ['country', 'year', 'A124_02_support', 'A124_06_support', 'A124_07_support', 'A124_08_support', 'A124_09_support', 'C002_support', 'E036_support', 'E037_support', 'E039_support', 'F114A_support', 'F115_support', 'F116_support', 'F117_support', 'F118_support', 'F119_support', 'F120_support', 'F121_support', 'F122_support', 'F123_support', 'G006_support', 'E069_01_support', 'E069_02_support', 'E069_04_support', 'E069_05_support', 'E069_06_support', 'E069_07_support', 'E069_08_support', 'E069_13_support', 'E069_17_support', 'A124_02_oppose', 'A124_06_oppose', 'A124_07_oppose', 'A124_08_oppose', 'A124_09_oppose', 'C002_oppose', 'E036_oppose', 'E037_oppose', 'E039_oppose', 'F114A_oppose', 'F115_oppose', 'F116_oppose', 'F117_oppose', 'F118_oppose', 'F119_oppose', 'F120_oppose', 'F121_oppose', 'F122_oppose', 'F123_oppose', 'G006_oppose', 'E069_01_oppose', 'E069_02_oppose', 'E069_04_oppose', 'E069_05_oppose', 'E069_06_oppose', 'E069_07_oppose', 'E069_08_oppose', 'E069_13_oppose', 'E069_17_oppose']
Wave 5 columns: ['country', 'year', 'A124_02_support', 'A124_06_support', 'A124_07_support', 'A124_08_support', 'A124_09_support', 'C002_support', 'E036_support', 'E037_support', 'E039_support', 'F114A_support', 'F115_support', 'F116_support', 'F117_support', 'F118_support', 'F119_support', 'F120_support', 'F121_support', 'F122_support', 'F123_support', 'G006_support', 'E069_01_support', 'E069_02_support', 'E069_04_support', 'E069_05_support', 'E069_06_support', 'E069_07_support', 'E069_08_support', 'E069_13_support', 'E069_17_support', 'A124_02_oppose', 'A124_06_oppose', 'A124_07_oppose', 'A124_08_oppose', 'A124_09_oppose', 'C002_oppose', 'E036_oppose', 'E037_oppose', 'E039_oppose', 'F114A_oppose', 'F115_oppose', 'F116_oppose', 'F117_oppose', 'F118_oppose', 'F119_oppose', 'F120_oppose', 'F121_oppose', 'F122_oppose', 'F123_oppose', 'G006_oppose', 'E069_01_oppose', 'E069_02_oppose', 'E069_04_oppose', 'E069_05_oppose', 'E069_06_oppose', 'E069_07_oppose', 'E069_08_oppose', 'E069_13_oppose', 'E069_17_oppose']
Wave 6 columns: ['country', 'year', 'A124_02_support', 'A124_06_support', 'A124_07_support', 'A124_08_support', 'A124_09_support', 'C002_support', 'E036_support', 'E037_support', 'E039_support', 'F114A_support', 'F115_support', 'F116_support', 'F117_support', 'F118_support', 'F119_support', 'F120_support', 'F121_support', 'F122_support', 'F123_support', 'G006_support', 'E069_01_support', 'E069_02_support', 'E069_04_support', 'E069_05_support', 'E069_06_support', 'E069_07_support', 'E069_08_support', 'E069_13_support', 'E069_17_support', 'A124_02_oppose', 'A124_06_oppose', 'A124_07_oppose', 'A124_08_oppose', 'A124_09_oppose', 'C002_oppose', 'E036_oppose', 'E037_oppose', 'E039_oppose', 'F114A_oppose', 'F115_oppose', 'F116_oppose', 'F117_oppose', 'F118_oppose', 'F119_oppose', 'F120_oppose', 'F121_oppose', 'F122_oppose', 'F123_oppose', 'G006_oppose', 'E069_01_oppose', 'E069_02_oppose', 'E069_04_oppose', 'E069_05_oppose', 'E069_06_oppose', 'E069_07_oppose', 'E069_08_oppose', 'E069_13_oppose', 'E069_17_oppose']
Wave 7 columns: ['country', 'year', 'A124_02_support', 'A124_06_support', 'A124_07_support', 'A124_08_support', 'A124_09_support', 'C002_support', 'E036_support', 'E037_support', 'E039_support', 'F114A_support', 'F115_support', 'F116_support', 'F117_support', 'F118_support', 'F119_support', 'F120_support', 'F121_support', 'F122_support', 'F123_support', 'G006_support', 'E069_01_support', 'E069_02_support', 'E069_04_support', 'E069_05_support', 'E069_06_support', 'E069_07_support', 'E069_08_support', 'E069_13_support', 'E069_17_support', 'A124_02_oppose', 'A124_06_oppose', 'A124_07_oppose', 'A124_08_oppose', 'A124_09_oppose', 'C002_oppose', 'E036_oppose', 'E037_oppose', 'E039_oppose', 'F114A_oppose', 'F115_oppose', 'F116_oppose', 'F117_oppose', 'F118_oppose', 'F119_oppose', 'F120_oppose', 'F121_oppose', 'F122_oppose', 'F123_oppose', 'G006_oppose', 'E069_01_oppose', 'E069_02_oppose', 'E069_04_oppose', 'E069_05_oppose', 'E069_06_oppose', 'E069_07_oppose', 'E069_08_oppose', 'E069_13_oppose', 'E069_17_oppose']

# LDA Application

In [87]:
import json
import pandas as pd
from sklearn.decomposition import LatentDirichletAllocation
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dictionary from JSON file
with open("variable_dict.json", "r", encoding="utf-8") as file:
    variable_dict = json.load(file)

# Assuming df_encoded is the DataFrame with the survey data after recoding.
# Let's inspect df_encoded for LDA
print(df_encoded.head())

     country  year  A124_02_support  A124_06_support  A124_07_support  \
7092     ARG  1999              0.0              0.0              0.0
7093     ARG  1999              0.0              0.0              0.0
7094     ARG  1999              0.0              0.0              1.0
7095     ARG  1999              0.0              0.0              0.0
7096     ARG  1999              0.0              0.0              0.0

      A124_08_support  A124_09_support  C002_support  E036_support  \
7092              0.0              0.0             0             0
7093              1.0              0.0             1             1
7094              1.0              1.0             1             1
7095              0.0              0.0             0             0
7096              0.0              0.0             1             0

      E037_support  ...  G006_oppose  E069_01_oppose  E069_02_oppose  \
7092             1  ...            0               0               1
7093             0  ...            0               0               1
7094             0  ...            0               0               1
7095             0  ...            0               1               1
7096             1  ...            0               1               1

      E069_04_oppose  E069_05_oppose  E069_06_oppose  E069_07_oppose  \
7092               1               1               1               1
7093               1               1               1               1
7094               1               1               1               1
7095               1               1               0               1
7096               0               1               1               1

      E069_08_oppose  E069_13_oppose  E069_17_oppose
7092               1               1               0
7093               1               1               0
7094               1               1               0
7095               1               0               0
7096               1               0               0

[5 rows x 60 columns]

In [ ]:
### Folders for the results

# Subfolders exist
# os.makedirs("../reports/lda_evaluation", exist_ok=True)
# os.makedirs("../reports/top_issues", exist_ok=True)

# Example for saving evaluation results
#eval_df.to_csv(f"reports/lda_evaluation/wave{wave_number}_evaluation.csv", index=False)

# Later when saving top issues:
#top_issues_df.to_csv(f"reports/top_issues/wave{wave_number}_top_issues.csv", index=False)

## Finding Optimal Number of Topics per Wave

In [88]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
import os
from itertools import combinations

# Setup
num_folds = 10
topic_range = range(1, 11)  # K = 1 to 10
data_folder = "data"
results_folder = "../reports/model_evaluation"
os.makedirs(results_folder, exist_ok=True)

def compute_npmi(issue_list, test_data):
    """Compute NPMI for a list of top issues using test data."""
    N = len(test_data)
    epsilon = 1e-10

    binary_data = test_data[issue_list].astype(int)
    issue_counts = binary_data.sum(axis=0).to_dict()

    npmi_scores = []
    for i, j in combinations(issue_list, 2):
        p_i = issue_counts[i] / N
        p_j = issue_counts[j] / N
        p_ij = ((binary_data[i] & binary_data[j]).sum()) / N

        if p_ij > 0:
            pmi = np.log(p_ij / (p_i * p_j + epsilon))
            npmi = pmi / (-np.log(p_ij + epsilon))
            npmi_scores.append(npmi)

    return np.mean(npmi_scores) if npmi_scores else 0

def evaluate_model_with_npmi(model, test_data, train_data):
    """Evaluate LDA model using average NPMI across all topics."""
    feature_names = train_data.columns
    topic_words = pd.DataFrame(model.components_, columns=feature_names)
    top_issues_per_topic = topic_words.apply(lambda x: x.nlargest(5).index.tolist(), axis=1)

    topic_npmis = [compute_npmi(issue_list, test_data) for issue_list in top_issues_per_topic]
    return np.mean(topic_npmis)

In [89]:
def process_wave_from_df(wave_number, df_wave):
    print(f"\n🌊 Processing Wave {wave_number}")

    # Drop metadata columns so that LDA only uses issue variables
    lda_data = df_wave.drop(columns=["country", "year"])

    # Initialize K-Fold cross-validator
    kf = KFold(n_splits=num_folds, shuffle=True, random_state=42)

    # To store NPMI evaluation scores across folds and topic numbers
    evaluation_matrix = np.zeros((num_folds, len(topic_range)))
    npmi_scores_per_topic = {k: [] for k in topic_range}

    # Cross-validation loop
    for fold_idx, (train_idx, test_idx) in enumerate(kf.split(lda_data)):
        print(f"📂 Fold {fold_idx + 1}/{num_folds}")

        train_data = lda_data.iloc[train_idx]
        test_data = lda_data.iloc[test_idx]

        for k_idx, n_topics in enumerate(topic_range):
            lda = LatentDirichletAllocation(
                n_components=n_topics,
                doc_topic_prior=0.25,
                topic_word_prior=0.1,
                learning_method='online',
                learning_decay=0.7,
                learning_offset=10.0,
                max_iter=20,
                batch_size=1000,
                evaluate_every=-1,
                mean_change_tol=0.001,
                max_doc_update_iter=100,
                n_jobs=-1,  # Uses all cores for this model
                random_state=25
            )
            lda.fit(train_data)

            # Evaluate using NPMI with held-out test data
            npmi_score = evaluate_model_with_npmi(lda, test_data, train_data)
            evaluation_matrix[fold_idx, k_idx] = npmi_score
            npmi_scores_per_topic[n_topics].append(npmi_score)

    # Compute the average NPMI across all folds for each topic count
    avg_npmis = {k: np.mean(npmi_scores_per_topic[k]) for k in topic_range}

    # Identify the optimal number of topics
    optimal_k = max(avg_npmis, key=avg_npmis.get)
    print(f"🏆 Optimal number of topics for Wave {wave_number}: K={optimal_k}")

    # Save evaluation results
    eval_df = pd.DataFrame(evaluation_matrix, columns=[f"K={k}" for k in topic_range])
    eval_df.to_csv(f"{results_folder}/wave{wave_number}_evaluation.csv", index=False)
    print(f"✅ Saved evaluation results for Wave {wave_number}")


# Run for waves 4–7 sequentially to avoid CPU overload
for wave_number, df in zip(range(4, 8), [df_wave4, df_wave5, df_wave6, df_wave7]):
    process_wave_from_df(wave_number, df)

print("\n🎯 Done! All waves processed using NPMI evaluation.")

🌊 Processing Wave 4
📂 Fold 1/10
📂 Fold 2/10
📂 Fold 3/10
📂 Fold 4/10
📂 Fold 5/10
📂 Fold 6/10
📂 Fold 7/10
📂 Fold 8/10
📂 Fold 9/10
📂 Fold 10/10
🏆 Optimal number of topics for Wave 4: K=4
✅ Saved evaluation results for Wave 4

🌊 Processing Wave 5
📂 Fold 1/10
📂 Fold 2/10
📂 Fold 3/10
📂 Fold 4/10
📂 Fold 5/10
📂 Fold 6/10
📂 Fold 7/10
📂 Fold 8/10
📂 Fold 9/10
📂 Fold 10/10
🏆 Optimal number of topics for Wave 5: K=7
✅ Saved evaluation results for Wave 5

🌊 Processing Wave 6
📂 Fold 1/10
📂 Fold 2/10
📂 Fold 3/10
📂 Fold 4/10
📂 Fold 5/10
📂 Fold 6/10
📂 Fold 7/10
📂 Fold 8/10
📂 Fold 9/10
📂 Fold 10/10
🏆 Optimal number of topics for Wave 6: K=3
✅ Saved evaluation results for Wave 6

🌊 Processing Wave 7
📂 Fold 1/10
📂 Fold 2/10
📂 Fold 3/10
📂 Fold 4/10
📂 Fold 5/10
📂 Fold 6/10
📂 Fold 7/10
📂 Fold 8/10
📂 Fold 9/10
📂 Fold 10/10
🏆 Optimal number of topics for Wave 7: K=3
✅ Saved evaluation results for Wave 7

🎯 Done! All waves processed using NPMI evaluation.

In [99]:
# Extract Topic-Feature Importance
feature_names = lda_data.columns
topic_words = pd.DataFrame(lda_model.components_, columns=feature_names)

# Normalize the Importance Scores
topic_words = topic_words.div(topic_words.sum(axis=1), axis=0)
topic_words = topic_words.T  # Transpose for better visualization
topic_words.columns = [f"Ideology_{i+1}" for i in range(num_topics)]

In [100]:
# Display Top Issues for Each Ideology
top_issues = topic_words.apply(lambda x: x.nlargest(10).index.tolist(), axis=0)
top_issues

# Save the descriptive DataFrame to a CSV file
top_issues.to_csv('top_issues.csv', index=False)

In [102]:
#### Ideology Groups per waves
from sklearn.decomposition import LatentDirichletAllocation
import pandas as pd

# Store optimal K values per wave (from your earlier evaluation)
optimal_k_per_wave = {
    4: 4,
    5: 7,
    6: 3,
    7: 3
}

# Map wave number to its corresponding cleaned dataframe
wave_data = {
    4: df_wave4,
    5: df_wave5,
    6: df_wave6,
    7: df_wave7
}

# Where to store the top issues per ideology
top_issues_by_wave = {}

# Process each wave
for wave_num, df in wave_data.items():
    print(f"\n🌊 Processing Wave {wave_num} with K={optimal_k_per_wave[wave_num]}")

    # Drop metadata columns to keep only issue positions
    lda_data = df.drop(columns=["country", "year"])

    # Refit LDA using optimal number of topics
    lda_model = LatentDirichletAllocation(
        n_components=optimal_k_per_wave[wave_num],
        learning_method='online',
        random_state=42
    )
    lda_model.fit(lda_data)

    # Extract topic-word matrix
    feature_names = lda_data.columns
    topic_words = pd.DataFrame(lda_model.components_, columns=feature_names)

    # Normalize importance scores (β values)
    topic_words = topic_words.div(topic_words.sum(axis=1), axis=0)
    topic_words = topic_words.T
    topic_words.columns = [f"Ideology_{i+1}" for i in range(optimal_k_per_wave[wave_num])]

    # Get top 10 issues for each ideology
    top_issues = topic_words.apply(lambda x: x.nlargest(10).index.tolist(), axis=0)
    top_issues_by_wave[wave_num] = top_issues

    # Save to CSV
    top_issues.to_csv(f"wave{wave_num}_top_issues_by_ideology.csv", index=False)
    print(f"✅ Saved top issues for Wave {wave_num}")

🌊 Processing Wave 4 with K=4
✅ Saved top issues for Wave 4

🌊 Processing Wave 5 with K=7
✅ Saved top issues for Wave 5

🌊 Processing Wave 6 with K=3
✅ Saved top issues for Wave 6

🌊 Processing Wave 7 with K=3
✅ Saved top issues for Wave 7

In [113]:
# For a given topic_words DataFrame (issue x topic β-values)
top_issues = topic_words.apply(lambda x: x.nlargest(10).index.tolist(), axis=0)

In [114]:
import json

# Load variable dictionary
with open("variable_dict.json", "r") as f:
    variable_dict = json.load(f)

# Extend it for support/oppose columns
extended_dict = {}
for var, label in variable_dict.items():
    extended_dict[f"{var}_support"] = f"{label} (Support)"
    extended_dict[f"{var}_oppose"] = f"{label} (Oppose)"

# Apply to top issues
labeled_top_issues = top_issues.apply(lambda col: col.map(extended_dict))

In [115]:
for wave_num, top_issues in top_issues_by_wave.items():
    # Map features to descriptions
    labeled_issues = map_features_to_labels(top_issues)

    # Save for reporting
    labeled_issues.to_csv(f"wave{wave_num}_top_issues_labeled.csv", index=False)
    print(f"✅ Labeled top issues saved for Wave {wave_num}")

✅ Labeled top issues saved for Wave 4
✅ Labeled top issues saved for Wave 5
✅ Labeled top issues saved for Wave 6
✅ Labeled top issues saved for Wave 7

/var/folders/vk/c6csf7ws6pj9wy406twfjkfw0000gn/T/ipykernel_31029/4239270483.py:15: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return top_issues_df.applymap(lambda x: extended_dict.get(x, x))  # fallback to original if not found

## Tables for the ideology issues

In [116]:
import pandas as pd

# Define the paths to your CSV files
files = {
    4: "wave4_top_issues_labeled.csv",
    5: "wave5_top_issues_labeled.csv",
    6: "wave6_top_issues_labeled.csv",
    7: "wave7_top_issues_labeled.csv"
}

# Load the CSV files into a dictionary of DataFrames, keyed by wave number.
top_issues_by_wave = {wave: pd.read_csv(path) for wave, path in files.items()}

In [117]:
for wave, df in top_issues_by_wave.items():
    print(f"Top Issues for Wave {wave}")
    display(df)  # In Jupyter Notebook, 'display' will show a nicely formatted table.

Top Issues for Wave 4

,Ideology_1,Ideology_2,Ideology_3,Ideology_4
0,Prostitution – justifiable? (Oppose),Confidence in Parliament (Oppose),Divorce – justifiable? (Support),Immigrants foreign workers as neighbors (Support)
1,Suicide – justifiable? (Oppose),Confidence in the Police (Oppose),Euthanasia – justifiable? (Support),People with AIDS as neighbors (Support)
2,Different race as neighbors (Oppose),Confidence in Civil Services (Oppose),Homosexuals as neighbors (Oppose),Homosexuals as neighbors (Support)
3,Homosexuality – justifiable? (Oppose),Confidence in Labour Unions (Oppose),People with AIDS as neighbors (Oppose),Different race as neighbors (Support)
4,Someone accepting a bribe – justifiable? (Oppose),Confidence in the Press (Oppose),Different race as neighbors (Oppose),Homosexuality – justifiable? (Oppose)
5,National pride (Support),Confidence in Major Companies (Oppose),Abortion – justifiable? (Support),Prostitution – justifiable? (Oppose)
6,Cheating on taxes – justifiable? (Oppose),Someone accepting a bribe – justifiable? (Oppose),Immigrants foreign workers as neighbors (Oppose),Drug addicts as neighbors (Support)
7,Abortion – justifiable? (Oppose),Suicide – justifiable? (Oppose),Homosexuality – justifiable? (Support),Suicide – justifiable? (Oppose)
8,Avoiding a fare on public transport – justifia...,Different race as neighbors (Oppose),National pride (Support),National pride (Support)
9,Justifiable: Claiming government benefits to w...,Cheating on taxes – justifiable? (Oppose),Someone accepting a bribe – justifiable? (Oppose),Preference for native workers in job scarcity ...

Top Issues for Wave 5

,Ideology_1,Ideology_2,Ideology_3,Ideology_4,Ideology_5,Ideology_6,Ideology_7
0,Homosexuality – justifiable? (Oppose),Immigrants foreign workers as neighbors (Support),Confidence in Parliament (Oppose),Confidence in Civil Services (Support),Avoiding a fare on public transport – justifia...,Euthanasia – justifiable? (Support),Confidence in the Police (Oppose)
1,Prostitution – justifiable? (Oppose),Different race as neighbors (Support),Confidence in Civil Services (Oppose),Confidence in Parliament (Support),Justifiable: Claiming government benefits to w...,Divorce – justifiable? (Support),Confidence in Armed Forces (Oppose)
2,Abortion – justifiable? (Oppose),People with AIDS as neighbors (Support),Confidence in the Church (Support),Confidence in Labour Unions (Support),Suicide – justifiable? (Support),Justifiable: Claiming government benefits to w...,Confidence in Justice System (Oppose)
3,Avoiding a fare on public transport – justifia...,Homosexuals as neighbors (Support),Confidence in Armed Forces (Support),Confidence in Justice System (Support),Cheating on taxes – justifiable? (Support),Someone accepting a bribe – justifiable? (Oppose),Confidence in the Press (Oppose)
4,Suicide – justifiable? (Oppose),Preference for native workers in job scarcity ...,Confidence in Labour Unions (Oppose),Confidence in Major Companies (Support),Euthanasia – justifiable? (Support),Different race as neighbors (Oppose),Confidence in Parliament (Oppose)
5,Someone accepting a bribe – justifiable? (Oppose),Justifiable: Claiming government benefits to w...,National pride (Support),Confidence in the Police (Support),Divorce – justifiable? (Support),Cheating on taxes – justifiable? (Oppose),Confidence in Civil Services (Oppose)
6,Cheating on taxes – justifiable? (Oppose),Homosexuality – justifiable? (Oppose),Suicide – justifiable? (Oppose),Confidence in the Press (Support),Someone accepting a bribe – justifiable? (Supp...,Avoiding a fare on public transport – justifia...,Confidence in Labour Unions (Oppose)
7,Drug addicts as neighbors (Support),Drug addicts as neighbors (Support),Someone accepting a bribe – justifiable? (Oppose),Confidence in Armed Forces (Support),Prostitution – justifiable? (Support),Immigrants foreign workers as neighbors (Oppose),Someone accepting a bribe – justifiable? (Oppose)
8,Euthanasia – justifiable? (Oppose),National pride (Support),People with AIDS as neighbors (Oppose),Confidence in the Church (Support),Drug addicts as neighbors (Support),Homosexuality – justifiable? (Support),Confidence in Major Companies (Oppose)
9,Justifiable: Claiming government benefits to w...,Prostitution – justifiable? (Oppose),Cheating on taxes – justifiable? (Oppose),Govt. responsibility vs. Individual responsibi...,Abortion – justifiable? (Support),Homosexuals as neighbors (Oppose),Suicide – justifiable? (Oppose)

Top Issues for Wave 6

,Ideology_1,Ideology_2,Ideology_3
0,Confidence in Armed Forces (Support),Confidence in Parliament (Oppose),Divorce – justifiable? (Support)
1,Prostitution – justifiable? (Oppose),Confidence in Civil Services (Oppose),Homosexuality – justifiable? (Support)
2,Confidence in Justice System (Support),Confidence in the Police (Oppose),Abortion – justifiable? (Support)
3,Suicide – justifiable? (Oppose),Confidence in Justice System (Oppose),Homosexuals as neighbors (Oppose)
4,Euthanasia – justifiable? (Oppose),Confidence in Labour Unions (Oppose),People with AIDS as neighbors (Oppose)
5,Confidence in the Police (Support),Confidence in the Press (Oppose),Different race as neighbors (Oppose)
6,Cheating on taxes – justifiable? (Oppose),Someone accepting a bribe – justifiable? (Oppose),Immigrants foreign workers as neighbors (Oppose)
7,Someone accepting a bribe – justifiable? (Oppose),Suicide – justifiable? (Oppose),National pride (Support)
8,National pride (Support),Euthanasia – justifiable? (Oppose),Confidence in the Police (Support)
9,Confidence in the Church (Support),Prostitution – justifiable? (Oppose),Drug addicts as neighbors (Support)

Top Issues for Wave 7

,Ideology_1,Ideology_2,Ideology_3
0,Confidence in Armed Forces (Support),Confidence in Parliament (Oppose),Divorce – justifiable? (Support)
1,Prostitution – justifiable? (Oppose),Confidence in Civil Services (Oppose),Euthanasia – justifiable? (Support)
2,Confidence in the Police (Support),Confidence in Justice System (Oppose),Homosexuality – justifiable? (Support)
3,Confidence in Justice System (Support),Confidence in the Press (Oppose),Homosexuals as neighbors (Oppose)
4,Suicide – justifiable? (Oppose),Confidence in Labour Unions (Oppose),Different race as neighbors (Oppose)
5,National pride (Support),Confidence in the Police (Oppose),Abortion – justifiable? (Support)
6,Confidence in Civil Services (Support),Confidence in Major Companies (Oppose),People with AIDS as neighbors (Oppose)
7,Someone accepting a bribe – justifiable? (Oppose),Someone accepting a bribe – justifiable? (Oppose),Immigrants foreign workers as neighbors (Oppose)
8,Cheating on taxes – justifiable? (Oppose),Suicide – justifiable? (Oppose),Drug addicts as neighbors (Support)
9,Confidence in the Church (Support),Prostitution – justifiable? (Oppose),Confidence in the Police (Support)

In [ ]:
### Mergin back the results to country and year 
for wave_df in [df_wave4, df_wave5, df_wave6, df_wave7]:
    lda_data = wave_df.drop(columns=["country", "year"])
    lda.fit(lda_data)
    topic_dist = lda.transform(lda_data)
    topic_df = pd.DataFrame(topic_dist, columns=[f"Topic_{i+1}" for i in range(topic_dist.shape[1])])
    merged = pd.concat([wave_df.reset_index(drop=True), topic_df], axis=1)

    # Optionally save it
    year_range = f"{wave_df['year'].min()}_{wave_df['year'].max()}"
    merged.to_csv(f"../reports/merged_wave_{year_range}.csv", index=False)

In [96]:
def summarize_top_issues_per_ideology(theta_df, phi_dict, vocab, top_n_topics=1, top_n_words=10):
    """
    Summarizes the top N features for each ideological type per wave.
    """
    summary = {}

    for wave in sorted(theta_df['wave'].unique()):
        wave_theta = theta_df[theta_df['wave'] == wave]
        phi = phi_dict[wave]

        wave_summary = {}

        for ideology in wave_theta['ideology'].unique():
            group = wave_theta[wave_theta['ideology'] == ideology]
            topic_cols = [col for col in group.columns if col.startswith("topic_")]

            # Average topic proportions for this ideology
            topic_means = group[topic_cols].mean().sort_values(ascending=False)

            # Select top N dominant topics
            top_topic_nums = [int(col.split("_")[1]) for col in topic_means.head(top_n_topics).index]

            keywords = {}
            for topic_num in top_topic_nums:
                word_probs = phi.loc[topic_num]
                top_word_indices = word_probs.sort_values(ascending=False).head(top_n_words).index
                top_keywords = [vocab[int(i)] for i in top_word_indices]
                keywords[f"Topic {topic_num}"] = top_keywords

            wave_summary[ideology] = keywords
        summary[wave] = wave_summary

    return summary

In [97]:
wave_summary = summary[4]  # For Wave 4
for ideology, topics in wave_summary.items():
    print(f"\n🧠 Ideology: {ideology}")
    for topic, keywords in topics.items():
        print(f"  📌 {topic}: {', '.join(keywords)}")

NameError: name 'summary' is not defined